services:
  - type: web
    name: ecommerce-visual-search
    env: python
    plan: free
    repo: ""
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run main.py --server.port $PORT --server.headless true --server.enableCORS false
